### PR TITLE
Zap crypto be

### PR DESCRIPTION
**Pull request by eoliveros**

### CODE REVIEW

**Comment by djpnewton** [comment]
Having all these `{%- if config["FLASK_ADMIN_SWATCH"] == "slate"%}` style if statements is not the best way to do it.

You should just check the config in the main layout template and then just add in a new css file to override the css values


Also if you update the branch you will see I have removed all the non-relevant premio stuff. We need to update the dashboard so it works with the new broker order models. Can you update the dashboard so it shows an overview of the broker orders (instead of the paydbtransactions and reward proposals/transactions)

**Comment by eoliveros** [comment]
did a pull and have to merged it manually.

**Comment by djpnewton** [comment]
also on the dashboard it would be good to see:
- the broker fee
- the supported assets and markets (from dasset.py)

**Comment by eoliveros** [comment]
> Having all these `{%- if config["FLASK_ADMIN_SWATCH"] == "slate"%}` style if statements is not the best way to do it.
> 
> You should just check the config in the main layout template and then just add in a new css file to override the css values
> 
> Also if you update the branch you will see I have removed all the non-relevant premio stuff. We need to update the dashboard so it works with the new broker order models. Can you update the dashboard so it shows an overview of the broker orders (instead of the paydbtransactions and reward proposals/transactions)

need to figure out why the "dashboard" is not loading. Then I will need to see the broker_order table, what it looks like when there is data in there.

**Pull request closed without merging**
